
// Defines the structure for a single skill, as generated by the AI.
export interface Skill {
  name: string;
  rating: number; // AI-rated proficiency from 1-5
  evidence: string; // Justification from the AI
}

// Defines the primary User profile structure, stored in Firestore.
// This reflects the new, AI-driven onboarding process.
export interface User {
  // Core user identity
  uid: string;
  name: string;
  email: string;
  
  // Academic & Professional Info
  branch: string;
  year: number;
  
  // Links to professional profiles (optional)
  githubUrl?: string;
  linkedinUrl?: string;
  leetcodeUrl?: string;
  photoURL?: string;

  // AI-Generated Profile Data (optional, added after async analysis)
  skills?: Skill[];
  profileSummary?: string;
  overallRating?: number; // AI-rated overall score from 1-5

  // Timestamps & Status
  createdAt: string; // Stored as an ISO string to be serializable
  lastSeen?: string; // For online status, stored as ISO string
}
